version: '3.7'

services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
  tempo:
    container_name: tempo
    image: grafana/tempo
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ '-config.file=/etc/tempo.yml' ]
    volumes:
      - ./config/tempo.yml:/etc/tempo.yml:ro
    ports:
      - 3200:3200    # tempo
      - 9411:9411    # zipkin
    networks:
      - monitoring
  grafana:
    build: 'config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:
